# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1091a6f0995bce5fe1df8d9b1c128ef9613f09a4b0209b0cd95564f9df0e234c9dd0970d16e8d5cd85575a4f7b1fce514fcd8a7645a255c4459a1203670c00

test:
  secret_key_base: 1fb34566395dd57e0c78b9a830133f1c9b189d2577aa1dbce4a07acafbe3f2697c00abd395cf7b765a5947efb75ec6bda3e0f26828062d48e3ce6bb893ceb9d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
